bump_version: null
lint: null
nf_core_version: 2.14.2.dev0
org_path: null
repository_type: pipeline
template:
  author: mirpedrol
  description: this is a plain nf-core pipeline template which will be customised
    afterwards with nf-core pipelines sync
  force: false
  is_nfcore: true
  name: plainnfcore
  org: nf-core
  outdir: .
  version: 1.0dev
  skip_features:
    - igenomes
update: null
